### ISSUE TITLE
install时超时

### ISSUE THREAD

**Issue by Hawyoo** [LiangYuxuan/bilibili-live-helper#1]
您好，我运行npm install后，总是卡在
`[#########.........] | reify:colors: timing reifyNode:node_modules/glob Completed in 1955ms`
随后报错
`npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.nlark.com/yocto-queue/download/yocto-queue-0.1.0.tgz failed, reason: connect ETIMEDOUT 10.69.4.40:808
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'`
请问该如何解决？

**Comment by LiangYuxuan** [comment]
这个挂梯子，或者换个淘宝镜像去装，有必要的话删除package-lock.json，应该能改善。

**Comment by LiangYuxuan** [comment]
删掉package-lock.json之后用淘宝镜像试试

**Comment by Hawyoo** [comment]
还是不行，毕竟我是个纯小白，可能有些地方还是不太合适

**Comment by LiangYuxuan** [comment]
把删掉package-lock.json之后用淘宝源的错误发一下

**Comment by Hawyoo** [comment]
[..................] / idealTree:bilibili-live-helper-master: sill idealTree buildDeps
只是一直卡在这一步，还没有报错

**Comment by LiangYuxuan** [comment]
呃，package-lock.json删了之后，node_modules也要记得删一下，然后再npm i

**Comment by Hawyoo** [comment]
是的，我都删了，之前卡在
[#########.........] | reify:colors: timing reifyNode:node_modules/glob Completed in 1955ms
这里的时候，node_modules只有几百k，我觉得大概率还是我这里的网络问题

**Comment by LiangYuxuan** [comment]
这可能是网络问题了

**Comment by Hawyoo** [comment]
那我再想想办法吧，打扰了，谢谢
